### ISSUE TITLE
[SUGGESTION] - Update to SAM 2

### ISSUE THREAD

**Issue by AlonDan** [hkchengrex/Cutie#100]
Will you please consider to update this wonderful project to use SAM 2 ?
Few days ago Meta released the model:

Meta's SAM 2:
https://ai.meta.com/sam2

**Comment by hkchengrex** [comment]
SAM 2 is parallel to Cutie. I am not sure what you mean by "update".

**Comment by AlonDan** [comment]
Sam 2 is the newest model released few days ago.
There are many new things that improved for example the accuracy and supporting for VIDEOS unlike SAM 1 (original) which wasn't built for videos but worked decent less accurate)

Since I'm not a programmer:
Can you please explain how to make SAM 2 works with Cutie?
Do I need to overwrite / update the new models only?

Are you sure that nothing of the code needs to change?

Cutie-Roto have a reference to my question [**READ HERE**](https://github.com/Zarxrax/Cutie-Roto/issues/4#issuecomment-2265059886)

**Comment by hkchengrex** [comment]
Hi, thank you for the update. I am aware of SAM 2. 

To clarify, this repo contains the supporting code of our research paper "Putting the Object Back Into Video Object Segmentation". SAM 2 is another research work/model in the same domain. SAM 2's paper also compared with our method. These are two different methods that have the same application. I hope you see why replacing our code in this repo with SAM 2 would not make sense.
