### ISSUE TITLE
Checkpoint double check

### ISSUE THREAD

**Issue by gogochen07** [hkchengrex/Cutie#103]
Hi, can I know if [cutie-base-image-pretrained.pth] and [cutie-base-mega.pth] are based on cutie or cutie+? Thanks!

**Comment by hkchengrex** [comment]
Cutie/Cutie+ differ only during inference. They share the same model weights.

**Comment by gogochen07** [comment]
Thanks for the clarification. Could I know how to enable the Cutie+ inference mode? Sorry I haven't found any instructions on this and want to make sure I run everything correctly.

**Comment by hkchengrex** [comment]
No worries.
https://github.com/hkchengrex/Cutie/blob/main/docs/EVALUATION.md -- "To evaluate with the "plus" setting, specify --config-name eval_plus_config.yaml immediately after python cutie/eval_vos.py before other arguments."
