### ISSUE TITLE
How to save labels for partial objects?

### ISSUE THREAD

**Issue by panyuxin1993** [hkchengrex/Cutie#104]
Since I need to label multiple objects per frame. Once I corrected the predicted masks for object A and propagate forward several frames later, I found masks for object B are wrong for many frames. If I go back to label object B and run propagate again, the masks for object A are gone and need to be mannually labeled again. Can I save the label of partial of the objects in a frame?

**Comment by hkchengrex** [comment]
We did not implement this feature. We require all annotations to be accurate when the propagation starts. This is because we do not provide a mechanism for distinguishing untouched good segments and ignored bad segments.
