### ISSUE TITLE
No module named `scripts.download_models`

### ISSUE THREAD

**Issue by aenoca** [hkchengrex/Cutie#105]
I installed the package using the command `pip install git+https://github.com/hkchengrex/Cutie.git`. When using the package outside, I notably used the command `from cutie.utils.get_default_model import get_default_model`, as in the `scripting_demo.py` file. When doing so, I get the aforementioned error in the file `cutie/utils/get_default_model.py' which uses the 'scripts/download_models.py' file. 

If I download the folder and `pip install -e .` then the issue disappears.

**Comment by hkchengrex** [comment]
Good catch. Thank you. I have moved the download script to within `cutie` and re-wrote the download path such that the weights folder is always relative to the cutie project path. The current code will save the weights outside of the project folder if it has been installed as a site package but that should be ok (not a good practice frankly but I don't want to change the existing code too much)
