### ISSUE TITLE
Real-Time/Streaming Support

### ISSUE THREAD

**Issue by siddk** [hkchengrex/Cutie#11]
Amazing work @hkchengrex! I’ve been looking at applying some of your work (XMem and now Cutie) to some of our real-time robotics applications.

I was wondering if you had any pointers/entry points for running Cutie in real-time (5-10 Hz) given a live camera feed. Any advice would be extremely appreciated!

**Comment by hkchengrex** [comment]
Hi, thanks a lot for your interest!
I think the [Colab demo](https://colab.research.google.com/drive/1yo43XTbjxuWA7XgCUO9qxAi7wBI6HzvP?usp=sharing) would be the best place to start. It presents an example of running Cutie on a `cv2.VideoCapture`. You might need other ways of giving the model the initial guiding mask(s) but that would be dependent on your application.

Please feel free to let me know if you run into any problems.

**Comment by siddk** [comment]
Brilliant, thanks so much @hkchengrex; one last question -- if I want to incrementally add object masks (strictly adding new object masks over time, with a maximum number of tracked objects in the 10-12 range), is there a nice way to do that?

Or is the simplest thing to do when I want to add a new object at some timestep just to spawn a separate thread that takes the current mask + new object mask, and start running CUTIE treating that new timestep as the "initial" step?

**Comment by hkchengrex** [comment]
You can just add new objects. 
In the `step` function: https://github.com/hkchengrex/Cutie/blob/1ab2ef0ae88a7b2c57f60c60ef80e090047c5fc8/cutie/inference/inference_core.py#L171-L198

You can provide the mask in the index format (e.g., in `eval_vos.py`) or the channel format (e.g., in the Colab demo). The index format is probably easier to work with for adding new objects. When you need to add some new objects, pass the mask to the `step` function, and pass `objects` as a list of object ids that you want to be considered in the mask. For example, you can pass all object ids if you think the segmentation is all correct at that frame (if this is the case, you might also want to use `force_permanent`), or you can just pass the new object id and ignore the rest.
