### ISSUE TITLE
Issue with YT VOS Evaluation

### ISSUE THREAD

**Issue by dfan** [hkchengrex/Cutie#114]
I tried uploading my YTVOS 2018 predictions to https://codalab.lisn.upsaclay.fr/competitions/7685 but nothing happened. I know you're not the competition organizer, but do you mind trying and letting me know if you're able to submit? 

Additionally, is there any way to get validation set results aside from submitting to the evaluation server?

**Comment by hkchengrex** [comment]
From https://github.com/codalab/codalab-competitions/issues/3503, using Firefox might solve the problem.
