### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by Z0721Z** [hkchengrex/Cutie#115]
If you train directly on a VOS dataset without using a static dataset, will the performance be significantly worse?

**Comment by hkchengrex** [comment]
In general static image pretraining helps a lot to kickstart main training.

**Comment by Z0721Z** [comment]
When training the model, if my dataset contains masks for all frames, do I need to process the dataset to include only masks for a few frames?

> 一般来说，静态图像预训练对启动主要训练有很大帮助。

**Comment by hkchengrex** [comment]
No.
