### ISSUE TITLE
Question regarding self.frame_image_transform in vos_dataset.py

### ISSUE THREAD

**Issue by jiangyu-comoco** [hkchengrex/Cutie#117]
![image](https://github.com/user-attachments/assets/304f3470-a7ad-4a92-b7b1-25d50c6e448e)

in Line 252 in vos_dataset.py, do we need to apply a new random seed before calling self.frame_image_transform(), otherwise each frame in the sequence would still receive the same set of color jitter parameters? Thanks.

**Comment by hkchengrex** [comment]
Nice catch! This indeed looks like a bug. We do seed it again with `np.random` (which itself does not get reseeded) in an earlier version of this code: https://github.com/hkchengrex/XMem/blob/a4427dbd748f66ed8fef159b529527e23060c666/dataset/vos_dataset.py#L145

Most likely, we introduced this bug during refactoring. All the models are trained with this version of `vos_dataset` though.
