### ISSUE TITLE
Visual Studio installation

### ISSUE THREAD

**Issue by SimmyCHN** [hkchengrex/Cutie#118]
请问有没有QQ群这样的频道，不知道visualatudio怎么安装，才能使用Cutie
![1727619900969](https://github.com/user-attachments/assets/8c6b9ba7-8f9a-4e22-ba2d-db8c8e40b1dd)
![VS的下载路径](https://github.com/user-attachments/assets/80496064-eb98-4c48-83d7-4e656b4b8a59)

**Comment by hkchengrex** [comment]
https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio
