### ISSUE TITLE
How to choose which model to use with model trained with customized dataset

### ISSUE THREAD

**Issue by panyuxin1993** [hkchengrex/Cutie#119]
When I start cutie using interactive GUI, by default it always use cutie-base-mega.pth in Cutie\weights. Even if I rename the model trained to this name, it will automatically download default cutie-base-mega.pth again. Should I change code somewhere or modify the pth file?

**Comment by hkchengrex** [comment]
Hi, you can change the path to weights here: https://github.com/hkchengrex/Cutie/blob/2a85b3ebf29a98958b8ecf670997b05e0118ff8e/cutie/config/gui_config.yaml#L12

**Comment by panyuxin1993** [comment]
Cool! Thank you! Very helpful!
