### ISSUE TITLE
Indicators of likelihood or difficulty for quick screening

### ISSUE THREAD

**Issue by panyuxin1993** [hkchengrex/Cutie#120]
Thank you for the wonderful tool. In my case, I found that the model performace is influenced by proximity of objects a lot. Sometimes, 2 or 3 or more objects occlued each other, which is very difficult conditions. When they separate several frames later, it is likely that some objects lose tracking. I wonder if the model can give a indicator of how good the model thinks it predicts for the current frame (e.g. likelihood, confidence, etc.), or indicators for difficulty (e.g. when object occlusion happens, this indicator can be higher). If so, maybe I can use this indicator to find specific frames that need manual check. Or maybe I can select frames before and after frames where objects get together and manually label them, then track forward from the frame before and track backward from the frame after to optimize the tracking. On the other hand, if I can select frames with high quality, maybe I can submit them into permenant memory to improve tracking?

**Comment by hkchengrex** [comment]
That would be a good-to-have but unfortunately our model did not implement this.
