### ISSUE TITLE
File Not Found in the Model Pre-trained Download Section

### ISSUE THREAD

**Issue by mahdiye-shamohammadi** [hkchengrex/Cutie#123]
Hello Rex
Thank you very much for sharing Cutie. Recently, I ran Cutie on Google Colab, and in the pre-trained model download section, the specified path does not exist, the specified python file python scripts/download_models.py  does not exist and this error message is appeared:[Errno 2] No such file or directory: '/content/Cutie'
/content 
python3: can't open file '/content/scripts/download_models.py': [Errno 2] No such file or directory
I would appreciate it if you could add this file to your GitHub
thank you

**Comment by hkchengrex** [comment]
1. It is `python cutie/utils/download_models.py` not `python scripts/download_models.py`
2. You need to `cd` into the Cutie repo before running the command
