### ISSUE TITLE
Training with custom data

### ISSUE THREAD

**Issue by gogochen07** [hkchengrex/Cutie#126]
Hi, could I know if there is an instructions on training with in-house private data? Currently, my data is under structure:
dataset
     -images
          -volume1
          ...
     -masks
          -volume1

if there any easy way to get start? Also I noticed in the training command line, the `data=[base/with-morse/mega]`, how to modify this if the data is from somewhere else? Thanks!

**Comment by hkchengrex** [comment]
The data configuration files are here: https://github.com/hkchengrex/Cutie/blob/main/cutie/config/data/base.yaml and https://github.com/hkchengrex/Cutie/blob/main/cutie/config/data/datasets.yaml

The data loading part is set up here: https://github.com/hkchengrex/Cutie/blob/main/cutie/dataset/setup_training_data.py and https://github.com/hkchengrex/Cutie/blob/main/cutie/dataset/vos_dataset.py
