### ISSUE TITLE
Running the CUTIE code for separating rain video

### ISSUE THREAD

**Issue by mahdiye-shamohammadi** [hkchengrex/Cutie#127]
Hello Rex,

Thank you very much for answering the previous question.

I would like to know if the CUTIE method works for a video of rain with the aim of separating raindrops. Have you tried it?

Additionally, if you know of any method that can achieve this goal, I would be very grateful if you could suggest it.

**Comment by hkchengrex** [comment]
I haven't tried this application but most likely it would be hard.
