### ISSUE TITLE
How to save the predicted images from inference

### ISSUE THREAD

**Issue by Z0721Z** [hkchengrex/Cutie#128]
I followed the "Inference and Evaluation" tutorial but still couldn't save the prediction results of my dataset.

**Comment by Z0721Z** [comment]
![image](https://github.com/user-attachments/assets/45e57837-f415-4164-8211-0fda68dc96af)

**Comment by hkchengrex** [comment]
The outputs should have been saved in the "output" directory.

**Comment by Z0721Z** [comment]
> The outputs should have been saved in the "output" directory.

Thank you for the author's patient response. I have one more question: I would like to know if the main training phase uses a semi-supervised approach, because I noticed that the data loading code seems to require all images in the dataset to have labels.

**Comment by hkchengrex** [comment]
The training process is not semi-supervised. Semi-supervised VOS refers to the inference process, where the first-frame ground-truth mask is given.
