### ISSUE TITLE
Improve mask deletion in GUI

### ISSUE THREAD

**Issue by beasteers** [hkchengrex/Cutie#13]
Thanks for you're great work on this family of models. 

One thing that is difficult with the UI is deleting object tracks once they have started. I tried resetting an object in a frame, but it's not trivial to propagate those deletions backward in time. 

Some suggestions:
 - show object presence over time - essentially a boolean grid of "objects" by "time" 
   - Have the ability to select and delete time ranges for a single object
 - have the ability to delete portions of the mask (have a mask brush)

**Comment by hkchengrex** [comment]
Hi, thank you for your interest.
Both of these are possible, but I don't have the capacity to implement them in the near future.
(If the propagation of deletion is difficult, you might want to clear the memory)
