### ISSUE TITLE
Batch Processing Videos

### ISSUE THREAD

**Issue by boardd** [hkchengrex/Cutie#130]
Hi, First of all, thank you for sharing this great work, I have found it extremely useful for my project.

I had a question about batch processing multiple videos. Is this possible and supported in the current code base? It would speed up the processing for me quite a bit.

**Comment by hkchengrex** [comment]
Thanks for using our project! The underlying network components support batched processing (we do so during training), but the memory manager for inference does not. It would be possible to extend it for batch processing, especially if the video inputs have the same resolution, but we didn't implement it.

**Comment by boardd** [comment]
thanks I will have a look
