### ISSUE TITLE
Congratulations on your new great work

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Cutie#18]
Congratulations on your new great work, I'm replicating your work, on the mose dataset, can you show what the correct format for mose submissions is? Like, what's the frame interval? What is the structure of the submitted file?

**Comment by hkchengrex** [comment]
Please refer to the official dataset page for the submission format: https://codalab.lisn.upsaclay.fr/competitions/10703
You can also download our pre-computed results.

**Comment by longmalongma** [comment]
> our pre-computed results.

Thanks, where is your pre-computed results on MOSE?

**Comment by hkchengrex** [comment]
https://github.com/hkchengrex/Cutie/blob/main/docs/EVALUATION.md
