### ISSUE TITLE
How to use the BURST dataset?

### ISSUE THREAD

**Issue by yahooo-m** [hkchengrex/Cutie#2]

**Comment by hkchengrex** [comment]
Download here: https://github.com/Ali2500/BURST-benchmark
I will add more information to the documentation.

**Comment by hkchengrex** [comment]
I have added some details on the placement of the BURST dataset. If it is placed in the expected directory, the code should work out-of-the-box. Please let me know if you run into any issues.

**Comment by yahooo-m** [comment]
Thanks for providing the details of BURST. I just want to use it to retain the model.
