### ISSUE TITLE
Inference speed/ memory optimisation

### ISSUE THREAD

**Issue by mzkaramat** [hkchengrex/Cutie#20]
Hi @hkchengrex , great work! May I ask, is it possible to optimise the inference in term of running at half precision fp16 by any chance, is the amp flag in config meant for it? And if you can give some pointers, if I want to quantise the model to maybe int8 (if that might be possible)? My motivation is to run the model at lower memory and using less GPU computation.

**Comment by hkchengrex** [comment]
Hi, "amp" is for [mixed precision](https://pytorch.org/docs/stable/notes/amp_examples.html) which is similar to but might be slightly more expensive than pure fp16. PyTorch also has a quantization API: https://pytorch.org/docs/stable/quantization.html

**Comment by mzkaramat** [comment]
thanks, it was more of a question then issue. Closing it,
