### ISSUE TITLE
Brush painting instead of auto segmentation

### ISSUE THREAD

**Issue by horsto** [hkchengrex/Cutie#24]
I am very eager to use Cutie in my projects since XMem worked so well for me. 

However, running cutie for the very first time in these days, I noticed that the function to "paint" on the image to create a mask seems to be gone from the new GUI used in cutie. 
That function was a very useful and important feature in my work with the XMem GUI, since the "left click - auto segmentation" frequently does not yield the right result and is tedious to refine on more complicated segmentation tasks. 

Could you implement the "paint brush" function again?

**Comment by hkchengrex** [comment]
Hi, thank you for the feedback. It seems that I underestimated the necessity of the other brushes... While there are no technical barriers to those functions, I am very occupied these days and won't be able to implement these in the near future.

**Comment by horsto** [comment]
Ok, I understand.
