### ISSUE TITLE
Change number of tracking objects while running cuties

### ISSUE THREAD

**Issue by pakcheera** [hkchengrex/Cutie#26]
This is very interesting work and it help me a lot in my  project. However, I would like to change the number of tracking objects but it show error. Cloud you suggest me about that?

**Comment by hkchengrex** [comment]
Adding new objects should work. I'm not sure what causes the error or what the error is, but if you want an example, you can take a look at YouTubeVOS18/19 evaluation: https://github.com/hkchengrex/Cutie/blob/main/docs/EVALUATION.md#video-object-segmentation
