### ISSUE TITLE
License for Commercial use

### ISSUE THREAD

**Issue by KaareLJensen** [hkchengrex/Cutie#28]
Thanks again for the great project.

As far as my test goes your project is working so much better and faster and is easier to use than any other similar I have been testing.

Is there any possibility to change the license to use the inference part of your project in a commercial product?

The current GPL-3.0 license, prevents doing that.

**Comment by hkchengrex** [comment]
Hello, 

GPL 3.0 does allow commercial usage. If you want a more permissive license, please drop me an email.
