### ISSUE TITLE
About pth --->ONNX 

### ISSUE THREAD

**Issue by songyang86** [hkchengrex/Cutie#29]
Dear   hkchengrex:
         When I convert pth to ONNX ,I'm confused by     self._add_memory       in inference_core.py. I just want to know how to  convert this function to ONNX.Thanks

**Comment by hkchengrex** [comment]
I don't have experience converting this to ONNX though I don't expect it to be trivial given the dynamic memory nature.

**Comment by HW140701** [comment]
> Dear hkchengrex: 亲爱的hk Chengrex： When I convert pth to ONNX ,I'm confused by self._add_memory in inference_core.py. I just want to know how to convert this function to ONNX.Thanks当我将 pth 转换为 ONNX 时，我对 inference_core.py 中的 self._add_memory 感到困惑。我只是想知道如何将此函数转换为ONNX。谢谢

hello, have you completed the onnx export?

**Comment by PredyDaddy** [comment]
> > Dear hkchengrex: 亲爱的hk Chengrex： When I convert pth to ONNX ,I'm confused by self._add_memory in inference_core.py. I just want to know how to convert this function to ONNX.Thanks当我将 pth 转换为 ONNX 时，我对 inference_core.py 中的 self._add_memory 感到困惑。我只是想知道如何将此函数转换为ONNX。谢谢
> 
> hello, have you completed the onnx export?

Hello, did you sucessfully export the onnx?
