### ISSUE TITLE
Errors installing on Windows

### ISSUE THREAD

**Issue by Zarxrax** [hkchengrex/Cutie#33]
Attempting to install this in windows results in errors related to the packages cchardet & netifaces.
I believe these packages may not be well maintained and only work on old versions of python. Can anyone confirm if they have had success installing Cutie in windows under a specific python version?

`ERROR: Failed building wheel for cchardet`
`ERROR: Failed building wheel for netifaces`

I found this alternate package for cchardet which allowed the installation to progress, but I have not found a solution for netifaces yet.
https://pypi.org/project/faust-cchardet/
Are these packages critical to the use of the application, or is it possible they could be removed?

**Comment by hkchengrex** [comment]
They are necessary in some installations though we do not explicitly use them. Feel free to comment them out to try.

**Comment by Zarxrax** [comment]
So after a lot of trial and error, I discovered that I can either use Python 3.8 to install it as provided, or I can replace the packages cchardet & netifaces with  faust-cchardet and netifaces-plus, respectively. Replacing those packages allows the install to complete successfully on later versions of python.

However, regardless of which option I went with, the application itself fails to run. Cython seems to be trying to compile something when the application is launched, is it is not able to do so successfully. I'm not sure exactly what packages its trying to compile or if there is another solution to download such packages rather than compiling them.

**Comment by hkchengrex** [comment]
For reference, I used Python 3.11 on Windows and had to install Visual Studio (with C++ build tools) to make it work. `pip` did give me an error about dependency resolver but it worked regardless. I did not have to modify the requirements.

I don't usually develop on Windows but I hope this helps.

**Comment by Zarxrax** [comment]
Aha, I finally got it.
I had previously tried installing the visual studio build tools thing, but I didn't understand what all needed to be selected in the install process, so it didn't do anything.

It would be great if this could get working easily on windows without needing to install 6+GB of compiler tools. A lot of non-technical people would love this tool.

**Comment by hkchengrex** [comment]
Glad to hear that it worked. I am not sure how to make the process easier (without significant customization) though.
