### ISSUE TITLE
Attempting to deserialize object on a CUDA

### ISSUE THREAD

**Issue by cyq329191721** [hkchengrex/Cutie#37]
I got a problem,yestorday,I test the project ,but it show the error : Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.What should id do?

**Comment by hkchengrex** [comment]
Are you trying to train? CPU-only training is not supported?

**Comment by cyq329191721** [comment]
> Are you trying to train? CPU-only training is not supported?

no,i'm not train,i have a model,but i only have cpu in my computer。

**Comment by hkchengrex** [comment]
Can you clarify what you are trying to do?

**Comment by CuriousTank** [comment]
`torch.cuda.is_available() `  must be False if you don't have a GPU device
