### ISSUE TITLE
Get list of frames committed to memory?

### ISSUE THREAD

**Issue by Zarxrax** [hkchengrex/Cutie#38]
Hi, I would like to add an indicator in the gui that can show which frames have been committed to memory.
I could not find in the code where you keep a list of the frames that are in memory. 
Can you advise how I can obtain that information?

**Comment by hkchengrex** [comment]
We do not keep an explicit list but I suppose you can implement one in the memory manager.

**Comment by Zarxrax** [comment]
Alright thanks,
it sounds a little complicated but I will look into it.
