### ISSUE TITLE
Soft Masks

### ISSUE THREAD

**Issue by Zarxrax** [hkchengrex/Cutie#41]
I noticed that when saving soft masks, the first frame where I start propagation from will have a binary mask instead of soft mask. Is there any way to correct that so I can get the soft mask on every frame?

Also, I was wondering if there is any way to get the benefits of both the softmask and binary mask together?
What I mean is, the binary mask follows the mask that is drawn in the gui perfectly, but the edges are rough and temporally unstable. Simply smoothing or blurring the edges doesn't look good because they are unstable.
The soft mask has fantastic edges and temporal stability! But there can be a lot of gray areas where things should be solid.
I think it would be amazing if I could get the mask which has solid areas which follow the gui, but also have the feathered edges with temporal stability like the softmasks. Do you have any idea how that can be achieved?

**Comment by hkchengrex** [comment]
1. The first frame is a binary mask even in the soft mask mode -- to be clear, does this happen because of the interaction happening in the first frame or because of the start of propagation? For example, if we back-propagate from the second frame to the first frame, does it give a soft mask for all frames?
2. Combining soft masks with binary masks -- this would require some ad-hoc post-processing. It might be possible by filtering the soft mask with a low threshold (e.g., `mask[mask<0.2] = 0`) but it would be dependent on your use case. Probably best to implement it as a post-processing step.

**Comment by Zarxrax** [comment]
1. If I propagate forward from from 0, then frame 0 will be a binary mask. If I now move to frame 1 and propagate backward, frame 0 will be a soft mask and frame 1 will be a binary mask. So whatever frame you start propagating from will become a binary mask. If I start and pause and start and pause, I will end up with multiple binary mask frames.

2. I think I came up with a good way to postprocess the frames using erosion and dilation and combining the binary and soft masks with each other. I'll test some more in a few days.

**Comment by Zarxrax** [comment]
I just wanted to follow up on this to say I was somewhat incorrect that the soft mask on the first frame of propagation being a binary mask. There is actually a difference between the binary mask and the soft mask that is saved on the first frame. I could not notice it on low resolution images, but on higher resolution images, the difference was more apparent. The soft mask somehow looks even more blocky than the regular mask, while having a very slight antialising on it, but not enough antialiasing to avoid the blockiness.
I am guessing maybe this blockiness and slight antialiasing is a result of the downsampling that occurs when doing propagation. I might suppose that taking the regular mask (which I guess doesn't go through downsampling) and adding a slight blur to it would end up being higher quality for these frames.

**Comment by hkchengrex** [comment]
Thank you for the update. Can you show some examples of that? I have been quite busy recently but I can take a look when I have the time.

**Comment by Zarxrax** [comment]
Sure, here are frames 0 and 1 from a sample. The regular mask (colored white instead of red), and the soft mask.

On frame 0, you can notice that the softmask looks lower resolution than the normal one.
![0000000m](https://github.com/hkchengrex/Cutie/assets/16127268/788de5f9-ad52-4a66-b5cd-050bc3db1d3c)
![0000000s](https://github.com/hkchengrex/Cutie/assets/16127268/780405f0-333e-4c84-8bf6-9c9f2073ed4d)

On frame 1, the soft mask has smooth soft edges.
![0000001m](https://github.com/hkchengrex/Cutie/assets/16127268/798e1a16-4174-4c14-8f3e-ad420faafc8c)
![0000001s](https://github.com/hkchengrex/Cutie/assets/16127268/11b12276-6182-4c14-b9a8-695aea83246e)

**Comment by hkchengrex** [comment]
Hi, I identified the problem but it is a bit hard to fix. The current solution skips saving the interacted frame and hence does not override previously saved frames. Hope that helps.

**Comment by charchit7** [comment]
Hey @Zarxrax could you please tell me how are you calculating mask for custom videos or images for testing?

**Comment by Zarxrax** [comment]
@charchit7, I'm sorry, I'm not sure I understand your question. Could you clarify what you mean?

**Comment by charchit7** [comment]
Yeah, sorry for the confusion. So basically what I mean is that, let's say you took a random video you want to test cutie on, how are you creating the first mask frame for it. I noticed that performance matters a lot on how you choose the masks.

**Comment by Zarxrax** [comment]
I just click on the image.

**Comment by charchit7** [comment]
without interactive mode? what if we want to create mask seperately?
