### ISSUE TITLE
Is permanent memory refers to longterm memory?

### ISSUE THREAD

**Issue by nnop** [hkchengrex/Cutie#43]
Thanks for this great work. 

I saw many operations on the permanent memory but didn't find description about it in the paper.
How is it used with other memories (sensory, working, long-term)?

**Comment by hkchengrex** [comment]
No. It is from [XMem++](https://github.com/max810/XMem2) as mentioned in the readme.

**Comment by nnop** [comment]
Thanks for pointing out the reference.
