### ISSUE TITLE
ModuleNotFoundError: No module named 'cutie'

### ISSUE THREAD

**Issue by AlonDan** [hkchengrex/Cutie#44]
I followed the installation everything went smooth until I tried to run:
`python interactive_demo.py`

I get this error:
```
(cutie) D:\AI\Cutie>python interactive_demo.py
Traceback (most recent call last):
  File "D:\AI\Cutie\interactive_demo.py", line 20, in <module>
    from gui.main_controller import MainController
  File "D:\AI\Cutie\gui\main_controller.py", line 20, in <module>
    from cutie.model.cutie import CUTIE
ModuleNotFoundError: No module named 'cutie'
```

I also tried this:
`pip install cutie`

But I still get the same error.

I'm not a programmer so I can't understand how to fix it,
Any suggestion how to fix that and make Cutie launch so I can test the demo?

Thanks ahead 🙏

**Comment by hkchengrex** [comment]
## Clone our repository:

```
git clone https://github.com/hkchengrex/Cutie.git
```

## Install with pip:

```
cd Cutie
pip install -e .
```

Did you do these?

**Comment by AlonDan** [comment]
Thanks for the reply,
Yes, I did it but for some reason the git clone didn't download all the files I think.
So what I did was to download manually the ZIP and I extracted it, then it worked :)
