### ISSUE TITLE
Question: Extract ALPHA result?

### ISSUE THREAD

**Issue by AlonDan** [hkchengrex/Cutie#45]
Is there a way to extract PNG Sequence or Video with the ALPHA of the result?

For example:
Tracked subject only Masked (soft or binary) without background, instead of using the alpha manually on a composite software.

If not, will you consider to add such feature? 🙏

**Comment by hkchengrex** [comment]
Do you mean like an RGBA png sequence output?

**Comment by AlonDan** [comment]
Yes, it will be very nice to test such feature! 🙏

Also, I found out about Cutie when I first saw XMem2 video demos and I noticed in these videos the GUI is a bit different, with very nice user friendly features:

1️⃣ - Magnifier / Zoom-In at the top right screen 

2️⃣ - Placing the POINTS (similar to SAM projects I saw) for Add / Remove
While in the current UI I use the Right mouse button to add and Right to Remove but I can't see any indication as feedback like the XMeme2 shows

My question based on the above, will you consider to add these UI or maybe other interesting GUI additions? 

I'm not a programmer but I have some ideas if you'll be interested to improve the project, I'll be happy to help 💙

**Comment by hkchengrex** [comment]
I have added RGBA output support. I like those functions from XMem2 but unfortunately I don't have the capacity to implement them any time soon.
