### ISSUE TITLE
Question: restarting inference.

### ISSUE THREAD

**Issue by ojh6404** [hkchengrex/Cutie#46]
First of all, I really appreciated for your great works.
I have a question about inference.

Im trying to integrate this model in my application and I wanna restart object tracking when trigger that provides new input mask and input image has been called.

It seems `clear_memory`, `clear_sensory_memory`  which are `InferenceCore`'s methods can work for this.
How can I clear memory of object and restart tracking?

Thanks!

**Comment by hkchengrex** [comment]
Hi.
If you want to reset everything, the easiest way might be just to create a new `InferenceCore` instance.
