### ISSUE TITLE
Question: How to change dilation radius / padding of mask?

### ISSUE THREAD

**Issue by realpixelbard** [hkchengrex/Cutie#50]
Hi Rex and team, thank you for making this useful tool. 🙏

May I know how do we change the dilation radius (also known as padding width) of the mask?

**Comment by hkchengrex** [comment]
Dilation should be done in post-processing -- for ProPainter, you can use the `--mask_dilation` argument when running ProPainter. In general, you can use OpenCV's `cv2.dilate`.
