### ISSUE TITLE
Not tracking properly

### ISSUE THREAD

**Issue by tonydavis629** [hkchengrex/Cutie#53]
Hi Rex I'm a big fan and user of your work.

I'm trying to get Cutie to work, but it seems to be failing to track my masks. I have the examples running fine, but when I try to apply this to a video of a drone, it totally fails.

Frame 1 (mask generated externally)
![VIS COLOR 1_000000](https://github.com/hkchengrex/Cutie/assets/84199903/a2259893-c7df-4f71-9bc2-becc469e3752)

Frame 4 (hasn't moved from initial position)
![VIS COLOR 1_000004](https://github.com/hkchengrex/Cutie/assets/84199903/290a02d9-f999-478b-ba72-e37c85196a7c)

Frame 37 (track begins to vanish)
![VIS COLOR 1_000037](https://github.com/hkchengrex/Cutie/assets/84199903/c2765eb2-570d-4b67-8eb0-fe877b59e5d8)

I've tried different configs, but no matter what Cutie seems to do this for this particular object. Do you have any idea what be the issue? I can use XMEM but Cutie seems more performant.

**Comment by hkchengrex** [comment]
This certainly looks unusual (esp. frame 4). Which script are you using?

**Comment by hkchengrex** [comment]
Similar things would happen if I forgot to sort the input frames (i.e., the script is reading the frames in some sort of random order, and the masks do not align with the input), so that might be happening here.

**Comment by tonydavis629** [comment]
I'm using scripting_demo.py. The images are in the correct order. The initial mask is generated from a object detector, so it wouldn't be because the mask files are loaded incorrectly.

**Comment by hkchengrex** [comment]
I see. Frame 4 looks like that the mask has a roughly correct shape but is offset. This is not a natural failure mode so there might be a bug. Could you please provide the first frame mask and the first four frames (up to frame 4 at least) so that I can investigate? Thanks!

**Comment by tonydavis629** [comment]
It turns out when I downsample from 4k to 1080, it works perfectly. I should have figured it wasn't trained on such a high resolution.

**Comment by hkchengrex** [comment]
Glad to see that it works now but that still should not be a failure mode even at very high resolution.

**Comment by tonydavis629** [comment]
I'm guessing it is something I changed in the config to compensate for OOM errors. I was getting OOM on a H100 80 gb in 2 frames... not sure if that is expected. But it certainly works better on 1080. 

Keep it up man your work is such a game changer!
