### ISSUE TITLE
convert interactive_demo to .exe

### ISSUE THREAD

**Issue by csustYyh** [hkchengrex/Cutie#54]
Thank you for your great work! 
I want to know if it is possible to convert .py to .exe for this work?
![image](https://github.com/hkchengrex/Cutie/assets/118873316/adfe5f53-c79e-4119-9563-d243eaa2eb03)

**Comment by hkchengrex** [comment]
Not an expert but https://stackoverflow.com/questions/5458048/how-can-i-make-a-python-script-standalone-executable-to-run-without-any-dependen
