### ISSUE TITLE
all zero output?

### ISSUE THREAD

**Issue by shippingwang** [hkchengrex/Cutie#57]
https://github.com/hkchengrex/Cutie/blob/2ac7ac21d048e7ff8b2b033a084e0e4ea7b1216c/cutie/inference/inference_core.py#L339C29-L339C40

I obtain all-zero outputs when running scripting_demo.py

**Comment by hkchengrex** [comment]
Are you using the script without modification? If so, updating PyTorch/just reinstalling it sometimes fixes it.

**Comment by shippingwang** [comment]
My fault, I thought it is a panoptic segmentation, only checking the border data(all zero), so it makes me confused
and now I have another question, if some interesting object disappear in the middle of a video, the Cutie will keep tracking it or not?
Thanks

**Comment by hkchengrex** [comment]
It should. Since that would be a harder case, it might fail more often.
