### ISSUE TITLE
Suggestions for minimizing memory reqs in high res video

### ISSUE THREAD

**Issue by tonydavis629** [hkchengrex/Cutie#59]
Hi Rex, do you have any insights into how the config should be optimized for high resolution videos to minimize memory requirements while maintaining performance? Ideally this would not modify the image size, because I am trying to track very small objects.

**Comment by hkchengrex** [comment]
This is still a hard problem in general. If the object does not go out of view, maybe using region-of-interest crops at every frame around the last segmentation can help.

**Comment by tonydavis629** [comment]
Interesting suggestion, thanks
