### ISSUE TITLE
Inference example

### ISSUE THREAD

**Issue by bhack** [hkchengrex/Cutie#61]
In the readme inference example, in the case we want to loop on more than one sequence can we recycle the inference processor. Is `clear_memory` enough to process a new video/sequence?

**Comment by hkchengrex** [comment]
You should create a new inference core for each new video (practically free). `clear_memory` is for when the memory becomes "corrupted" and the user wants a clean slate while tracking the same set of objects.

**Comment by bhack** [comment]
ok thanks.
