### ISSUE TITLE
How to debug this distributed training code

### ISSUE THREAD

**Issue by Clei-wl** [hkchengrex/Cutie#63]
![image](https://github.com/hkchengrex/Cutie/assets/63575090/f7e7c26f-fc00-4ee5-a85a-94a285bc138b)
![image](https://github.com/hkchengrex/Cutie/assets/63575090/8afdc22f-f611-4fe2-9c7c-97a2eff0ef38)

When I use Pycharm to debug this project, the second pic is my remote configuration.

Can you tell me how to fix this problem?
Thank you very much!

**Comment by hkchengrex** [comment]
Please use the provided training command: https://github.com/hkchengrex/Cutie/blob/main/docs/TRAINING.md#training-command
