### ISSUE TITLE
run scripting_demo.py outof Mem, but run gui， it is ok

### ISSUE THREAD

**Issue by darrenlei123** [hkchengrex/Cutie#66]
![微信图片_20240514212253](https://github.com/hkchengrex/Cutie/assets/98946974/8250c244-0e3c-4c2e-acf1-f9d82dbcbf7b)

**Comment by darrenlei123** [comment]
please help me, anyone is ok.

**Comment by hkchengrex** [comment]
We would need more information. Have you tried running the script unmodified?

**Comment by hkchengrex** [comment]
Please feel free to re-open if there is more information.
