### ISSUE TITLE
Simple cli inference script

### ISSUE THREAD

**Issue by KaareLJensen** [hkchengrex/Cutie#7]
Great work !

Will you provide a simple command line interface to process a video/images of video given object mask(s)?
Maybe something like done for XMem++: https://github.com/max810/XMem2#use-xmem-command-line-and-python-interface

I can see that eval_vos.py provides for something like this using dataset=generic, but this script seems more to be for big batch processing of datasets.

**Comment by hkchengrex** [comment]
`eval_vos.py` works for a single video (putting just one video in the dataset).
The GUI also works for single video testing.
Our [Colab demo](https://colab.research.google.com/drive/1yo43XTbjxuWA7XgCUO9qxAi7wBI6HzvP?usp=sharing) shows how to use the codebase for evaluating on a single video.

I agree that having a command line interface for single video evaluation (with potentially multiple permanent memory frames) can be useful. Pull requests are welcomed.

**Comment by KaareLJensen** [comment]
Thanks for your response.
If I succeed in creating a CLI script for single video evaluation, I will try to create a PR.
I will return to the Colab demo for inspiration ;-)

**Comment by KaareLJensen** [comment]
Now added a PR with new CLI script to run on video file #16 
Hope it can be used 🙂
