### ISSUE TITLE
pre_training vs. main_training

### ISSUE THREAD

**Issue by Huster-Hq** [hkchengrex/Cutie#71]
What's the difference between 'pre_training' and 'main_training'?

**Comment by hkchengrex** [comment]
Please refer to Section 3.5 in STM https://arxiv.org/abs/1904.00607, or Section 3.4.3 in our paper.

**Comment by Huster-Hq** [comment]
> Please refer to Section 3.5 in STM https://arxiv.org/abs/1904.00607, or Section 3.4.3 in our paper.

Thanks!
