### ISSUE TITLE
How to Start Tracking from an Internal Frame and Track Bidirectionally 

### ISSUE THREAD

**Issue by HitLyn** [hkchengrex/Cutie#75]
Hi,

Great job! Thank you for providing the model and the comprehensive demo script. I am currently working on a project where I need to start tracking from an intermediate frame, track to the end frame, and then backtrack from this intermediate frame back to the beginning frame. I am facing issues in implementing this due to memory and initialization concerns.

Here is the script I have written so far:

```
@torch.inference_mode()
@torch.cuda.amp.autocast()
def BidirectionalTracking(initial_masks, img_data_all, intermediate_frame):

    cutie = get_default_model()
    processor = InferenceCore(cutie, cfg=cutie.cfg)

    num_frames = len(img_data_all)

    # Convert the intermediate frame image data to a tensor
    initial_image_data = img_data_all[intermediate_frame]
    initial_image = Image.fromarray(initial_image_data.astype(np.uint8))
    initial_image = to_tensor(initial_image).cuda().float()

    # Initialize the mask for the intermediate_frame
    initial_mask = torch.from_numpy(initial_masks).cuda()

    # Get unique objects (excluding background)
    objects = np.unique(initial_mask.cpu().numpy())
    objects = objects[objects != 0].tolist()
    
    # Process frames from the intermediate_frame to the end
    for idx in range(intermediate_frame, num_frames):
        image_data = img_data_all[idx]
        image = Image.fromarray(image_data.astype(np.uint8))
        image = to_tensor(image).cuda().float()

        if idx = intermediate_frame:
            output_prob = processor.step(initial_image, initial_mask, objects=objects)
        if idx != intermediate_frame:
            # Propagate the mask from memory for subsequent frames
            output_prob = processor.step(image)

    # Process frames from the intermediate_frame back to the beginning
    if intermediate_frame > 0:
        for idx in range(intermediate_frame - 1, -1, -1):
            image_data = img_data_all[idx]
            image = Image.fromarray(image_data.astype(np.uint8))
            image = to_tensor(image).cuda().float()

            # Propagate the mask from memory
            output_prob = processor.step(image)

    return
```

Could you please provide guidance on how to modify the script to achieve this functionality? Your help would be greatly appreciated.

**Comment by HitLyn** [comment]
As the order of the images is important, should I clear the memory in some way after the first round of tracking and reinitialize the model before tracking back to the beginning?

**Comment by hkchengrex** [comment]
> As the order of the images is important, should I clear the memory in some way after the first round of tracking and reinitialize the model before tracking back to the beginning?

Yes. The simplest way would be to start two independent tracks -- one forward and one backward.

**Comment by HitLyn** [comment]
Do you mean I need to initialize twice, like:
```
cutie1 = get_default_model()
processor1 = InferenceCore(cutie, cfg=cutie.cfg)
cutie2 = get_default_model()
processor2 = InferenceCore(cutie, cfg=cutie.cfg)
```

**Comment by hkchengrex** [comment]
You only need one `cutie` instance as it does not contain memory. For `InferenceCore`, you can use multiple but it would be best practice to delete (with garbage recycle) the previous one before using the next one to save memory.

**Comment by HitLyn** [comment]
> You only need one `cutie` instance as it does not contain memory. For `InferenceCore`, you can use multiple but it would be best practice to delete (with garbage recycle) the previous one before using the next one to save memory.

Thanks a lot. That helps!
