### ISSUE TITLE
CVPR 2024 Mose Challenge

### ISSUE THREAD

**Issue by bhack** [hkchengrex/Cutie#76]
I don't know if you are interested but the 1st solution in the CVPR 2024 challenge it seems a small CUTIE adaptation
https://arxiv.org/abs/2406.04600

And also the 3d place it was a CUTIE adaptation
https://arxiv.org/abs/2406.03668

**Comment by hkchengrex** [comment]
Interesting. Thank you for letting me know!
Congrats to them 😄

**Comment by bhack** [comment]
They are not very detailed but probably some trick it could still be still useful to be adopted here.

**Comment by hkchengrex** [comment]
I am happy to see and sure there will be future developments on better mask tracking. I would gladly take pull requests but unfortunately my current research focus is elsewhere. Thank you for your support and suggestion.

**Comment by bhack** [comment]
P.s. also the 2nd solution so 3/3 :wink:
