### ISSUE TITLE
Question on Cutie's Arxiv paper equation S2

### ISSUE THREAD

**Issue by zzzc18** [hkchengrex/Cutie#77]
I'm confused about this S2 equation, seems it's not equivalent to S1. And I noticed a comment in object_transformer.py says:
```python
# during inference, T=1 as we already did streaming average in memory_manager
```

I'm wondering if it would be better to remove the T in S2 or specify as the current timestep? (If I'm understanding correctly)

**Comment by hkchengrex** [comment]
They are both computing averages. `T=1` in (S2).

**Comment by zzzc18** [comment]
Thanks for explaining!
