### ISSUE TITLE
Use specified device type to use CPU only

### ISSUE THREAD

**Issue by ashishp03** [hkchengrex/Cutie#79]
What is the way to specify the device type, for example, if I want to specifically use the CPU, how can I change the code to fit this?

**Comment by hkchengrex** [comment]
We officially only support CUDA. I believe it should not be too hard to hack it to work on CPU, e.g., by changing https://github.com/hkchengrex/Cutie/blob/e869fab5e653b118c475cbafe0b2322b37a7e320/cutie/utils/get_default_model.py#L23

and other `.cuda()` calls in the scripting demo.

**Comment by hkchengrex** [comment]
Please feel free to re-open if there are any updates.
