### ISSUE TITLE
can not get the first_frame.png

### ISSUE THREAD

**Issue by zyz-code** [hkchengrex/Cutie#80]
我运行的colab的代码，为什么我访问不到那个网站，无法获取那张图片
!wget -O video.mp4 https://user-images.githubusercontent.com/7107196/177661140-f690156b-1775-4cd7-acd7-1738a5c92f30.mp4
!wget -O first_frame.png https://i.imgur.com/3ueaiBA.png

video_name = 'video.mp4'
mask_name = 'first_frame.png'

这是报错信息
--2024-06-24 12:53:07--  https://i.imgur.com/3ueaiBA.png
Resolving i.imgur.com (i.imgur.com)... 199.232.192.193, 199.232.196.193
Connecting to i.imgur.com (i.imgur.com)|199.232.192.193|:443... connected.
HTTP request sent, awaiting response... 429 Unknown Error
2024-06-24 12:53:08 ERROR 429: Unknown Error.

**Comment by zyz-code** [comment]
我下载下来自己上传了之后改了一下路径就可以了，但是为什么会那么报错呢

**Comment by hkchengrex** [comment]
imgur might have temporarily blocked the image/your IP. Not much I can do here.
