### ISSUE TITLE
why my using device is cpu?

### ISSUE THREAD

**Issue by nirvanaYu777** [hkchengrex/Cutie#81]
I've got NVidia 4090 and setup all the requirements include cuda,pytorch etc.   
My system is windows 11. This is the message:
E:\XMem2\Cutie\Cutie>python interactive_demo.py --video ./examples/6.mp4 --num_objects 3
Using device: cpu
Single object: False
Workspace is in: ./workspace\6
5397 images found.

**Comment by hkchengrex** [comment]
What do you get when you run `python -c "import torch; print(torch.cuda.is_available())"`?

**Comment by hkchengrex** [comment]
Please feel free to re-open if there are any updates.
