### ISSUE TITLE
Change color for objects in GUI?

### ISSUE THREAD

**Issue by ZHANGTIANYAO1** [hkchengrex/Cutie#82]
Can I change color for object inside GUI? currently I cannot find any setting allow me to do that.

**Comment by hkchengrex** [comment]
Do you mean the colors for visualizations? You can change the palette here: https://github.com/hkchengrex/Cutie/blob/a9cad9acdd3bcb027e48e276547b9766312d8326/gui/interactive_utils.py#L42
