### ISSUE TITLE
How to solve this problem: "This plugin does not support propagateSizeHints()"?

### ISSUE THREAD

**Issue by luoshuiyue** [hkchengrex/Cutie#83]
The program is stuck here: 
![微信图片_20240701170439](https://github.com/hkchengrex/Cutie/assets/25098355/014734be-9810-46ae-a603-d74a1ab0d0e5)
![微信图片_20240701153339](https://github.com/hkchengrex/Cutie/assets/25098355/292552db-86a1-4708-b063-b629e4477872)

**Comment by hkchengrex** [comment]
It is not a fatal error: https://stackoverflow.com/questions/69927654/this-plugin-does-not-support-propagatesizehints-calling-exec-on-qdialog

Are you running it on a remote server or a local machine?

**Comment by luoshuiyue** [comment]
> It is not a fatal error: https://stackoverflow.com/questions/69927654/this-plugin-does-not-support-propagatesizehints-calling-exec-on-qdialog
> 
> Are you running it on a remote server or a local machine?

I run it on a local machine.
![微信图片_20240702094029](https://github.com/hkchengrex/Cutie/assets/25098355/77481193-31ac-4742-a52a-dd1aef3442a9)

**Comment by luoshuiyue** [comment]
> It is not a fatal error: https://stackoverflow.com/questions/69927654/this-plugin-does-not-support-propagatesizehints-calling-exec-on-qdialog
> 
> Are you running it on a remote server or a local machine?

I run it on a local machine.
![Uploading 微信图片_20240702094029.png…]()

**Comment by luoshuiyue** [comment]
> It is not a fatal error: https://stackoverflow.com/questions/69927654/this-plugin-does-not-support-propagatesizehints-calling-exec-on-qdialog
> 
> Are you running it on a remote server or a local machine?

I run it on a local machine.
![微信图片_20240702094029](https://github.com/hkchengrex/Cutie/assets/25098355/65dfaf81-8f3c-46da-95bf-8d273718d469)

**Comment by hkchengrex** [comment]
Thanks for the update.
1. Can you use Cutie instead of MiVOS for this test? Cutie has a more up-to-date codebase.
2. Can you try `export QT_QPA_PLATFORM=xcb` before running `interactive_demo.py`? -- It seems the program is running correctly but the GUI is not displayed for some reason.

**Comment by luoshuiyue** [comment]
> Thanks for the update.
> 
> 1. Can you use Cutie instead of MiVOS for this test? Cutie has a more up-to-date codebase.
> 2. Can you try `export QT_QPA_PLATFORM=xcb` before running `interactive_demo.py`? -- It seems the program is running correctly but the GUI is not displayed for some reason.

Thank you so much! It works.
![微信图片_20240702101039](https://github.com/hkchengrex/Cutie/assets/25098355/999d3ab2-7078-4604-94cd-ffbd19f0fd65)
