### ISSUE TITLE
GUI and scripting demo get different tracking results with a same initial mask

### ISSUE THREAD

**Issue by HitLyn** [hkchengrex/Cutie#85]
I get different results when using the interactive GUI and running the script with the same binary mask. It looks like some threshold configurations are different between the two methods. How to get the same tracking result as the GUI, it is cleaner and more stable.

For reference, I use the upload mask function in the interactive GUI, and the mask image is saved from the same binary array used in the script, but the results are different. Are there any specific configurations used in the GUI that are different from the given script?

Thanks for the great project.

https://github.com/hkchengrex/Cutie/assets/25073978/74ff8c5e-aa40-41c9-8b8c-a701ff19b7db

https://github.com/hkchengrex/Cutie/assets/25073978/1e0324d1-e2a6-45e7-b851-db18c7f86834

**Comment by HitLyn** [comment]
https://github.com/hkchengrex/Cutie/assets/25073978/1e0324d1-e2a6-45e7-b851-db18c7f86834

**Comment by HitLyn** [comment]
For reference, I use the upload mask function in the interactive GUI, and the mask image is saved from the save binary array used as the script, but the results are different.

**Comment by hkchengrex** [comment]
One reason might be that we resize the frames such that the shorter side has 480 pixels in the GUI but we do not do the same for the scripting demo. Can you verify if that's the case? Please try adding
```
processor.max_internal_size = 480
```
right after the initialization of `InferenceCore`

**Comment by HitLyn** [comment]
> One reason might be that we resize the frames such that the shorter side has 480 pixels in the GUI but we do not do the same for the scripting demo. Can you verify if that's the case? Please try adding
> 
> ```
> processor.max_internal_size = 480
> ```
> 
> right after the initialization of `InferenceCore`

This works! Thanks a lot. 
The _**align_corners**_ parameter here needs to be dropped to avoid the error: **_valueerror: align_corners option can only be set with the interpolating modes: linear | bilinear | bicubic | trilinear_**
https://github.com/hkchengrex/Cutie/blob/a9cad9acdd3bcb027e48e276547b9766312d8326/cutie/inference/inference_core.py#L224

**Comment by hkchengrex** [comment]
Thanks for the report! I have fixed this bug and added the option to change the `max_internal_size` in the scripting demo.
