### ISSUE TITLE
Selecting a video inside the GUI

### ISSUE THREAD

**Issue by Sillyyk** [hkchengrex/Cutie#87]
Thank you for your excellent work.

I want to ask where the input entrance for the video is, but I don't seem to be able to find it in "gui. py". I want to display the interactive interface first, and then select the video to open for operation.

**Comment by hkchengrex** [comment]
We did not implement this function.

**Comment by Sillyyk** [comment]
thanks for your reply.Can I write a 'button' in the GUI to override the input 'controller', or can I only modify it from the input in 'config'?

**Comment by haduoken** [comment]
simple add a button widget in qt will help

**Comment by Sillyyk** [comment]
thanks for your advise.I have completed this operation.
