### ISSUE TITLE
'a mask prediction' in Sec. 3.2.2 of Paper

### ISSUE THREAD

**Issue by Huster-Hq** [hkchengrex/Cutie#88]
Is the mask prediction single channel, i.e., H×W×1?

![image](https://github.com/hkchengrex/Cutie/assets/100923014/d345c1a5-fde7-490a-8869-9837c77aa74b)

**Comment by hkchengrex** [comment]
Yes.

**Comment by Huster-Hq** [comment]
I have a question about the detales of _**Object Memory**_：
1. The object memory are computed by _**N**_ pooling masks. However, these pooling masks do not have a constraint label, unlike the mask $M_l$ projected from the pixel features constrained by GT mask. I can't understand the information contained in these pooling masks and why one half can be foreground predictions and the other half is background predictions.  I wonder if you have directly visualized these masks.

**Comment by hkchengrex** [comment]
What do you mean by "constraint label"? W is directly constructed from M_l in the screenshot that you provided. There are no additional transformations. Those masks are just the masks in Figure 4 (and their inverse).

**Comment by Huster-Hq** [comment]
Isn't $W$ generated by the memory feature $F$ through a MLP?
![image](https://github.com/user-attachments/assets/34241189-78e6-4526-a0d2-9a204d4ca5c7)

**Comment by Huster-Hq** [comment]
> What do you mean by "constraint label"? W is directly constructed from M_l in the screenshot that you provided. There are no additional transformations. Those masks are just the masks in Figure 4 (and their inverse).
Figure 4 shows the $M_l$ rather than pooling masks $W$.

**Comment by hkchengrex** [comment]
Oh, right. Sorry -- it slipped my mind. We have visualized them before at some point. IIRC those masks are rather diffuse and don't have very recognizable patterns. They are learned end-to-end.
