### ISSUE TITLE
interactive tool for data annotation

### ISSUE THREAD

**Issue by lpy523** [hkchengrex/Cutie#89]
Thanks for your excellent work! Is it possible to use the interactive tool to generate instance segmentation annotations in COCO format for my own dataset?

**Comment by hkchengrex** [comment]
Of course. You would need to convert the mask to the COCO format: 

https://github.com/cocodataset/cocoapi/issues/131

https://stackoverflow.com/questions/68663512/image-segmentation-mask-to-polygon-for-coco-json
