### ISSUE TITLE
how to maintain the original resolution

### ISSUE THREAD

**Issue by luoshuiyue** [hkchengrex/Cutie#90]
Hello! I used Cutie to find that after extracting 3K image mask, both images and masks became 1k image, is there any way to maintain the original resolution?

**Comment by hkchengrex** [comment]
Yes. Change it here: https://github.com/hkchengrex/Cutie/blob/d24ab454886b5253ab5df1a5c0c9618f1b95b7e9/cutie/config/gui_config.yaml#L22

**Comment by luoshuiyue** [comment]
Thanks very much! It works.
