### ISSUE TITLE
Automated processing script

### ISSUE THREAD

**Issue by luoshuiyue** [hkchengrex/Cutie#91]
Hello, does the code support automatic mask extraction without human interaction, or how can I make simple changes to the code to extract mask based on prompt such as text prompt.

**Comment by hkchengrex** [comment]
On a high level, we have something like this: https://github.com/hkchengrex/Tracking-Anything-with-DEVA which is quite a complicated pipeline supporting new objects and different base models.

For something simpler like detection at the first frame + propagation, you can start with the scripting demo (by replacing `mask` with your automatic generation).

**Comment by hkchengrex** [comment]
Feel free to re-open if there are any updates.
