### ISSUE TITLE
Propagating mask based on an arbitrary frame?

### ISSUE THREAD

**Issue by royvelich** [hkchengrex/Cutie#92]
Is it possible to provide a mask image given in an arbitrary frame index? and not necessarily the first frame.

**Comment by hkchengrex** [comment]
The easiest way is to provide a mask for that frame and then do (independent) forward and backward propagation. This is also how it is done in the GUI.

**Comment by hkchengrex** [comment]
Both passes will be ID-consistent with their "initial" frame. So if the same initial frame is used, the two passes will have consistent IDs.

**Comment by hkchengrex** [comment]
Feel free to re-open if there are any updates.
