### ISSUE TITLE
Weights saving -  Best/Last  checkpoints ?

### ISSUE THREAD

**Issue by kassimi98** [hkchengrex/Cutie#93]
Hi hkchengrex, Thank you for your work.

We trained Cutie during the pre-training phase for 80,000 iterations and ended up with an `exp_id_pretraining_last.pth` file. The model saves a `.pth` file every 10,000 iterations, overwriting the previous one.

I have a couple of questions:
1. Is the saved pre-trained model the last one or the best one?
2. How can we evaluate the quality of training in both the pre-training and main-training phases using our own dataset?
3. If the saved model is the last one, how can we configure it to save the best model instead?

**Comment by hkchengrex** [comment]
Hi, thanks for the question.

1 -- The last one.
2/3 -- Model selection and validation during training are not implemented here. I'm afraid that you would have to implement your own

**Comment by kassimi98** [comment]
Thank you
