### ISSUE TITLE
Encounter error: ValueError: failed in converting 7th argument `g' of _lbfgsb.setulb to C/Fortran array

### ISSUE THREAD

**Issue by luoshuiyue** [hkchengrex/Cutie#98]
I reconstruct a new environment, when run `python interactive_demo.py --images v00_undistort --num_objects 1`, it still can works but tends to get stuck when I click on the picture. Above is some wanring and error:
![1722590417807](https://github.com/user-attachments/assets/86d829c1-9837-4eb1-b7da-1f1d755e11bf)
![1722590435549](https://github.com/user-attachments/assets/4d64aa72-31b1-41b5-bdfb-7c8c61d2f27f)
![1722590455946](https://github.com/user-attachments/assets/e6943339-95bf-412b-b5db-94f218c1fb5f)

**Comment by hkchengrex** [comment]
See: https://github.com/hkchengrex/Cutie/issues/84

As far as I know, this error is from the interactive segmentation library instead of our code. I cannot reproduce this problem and do not have a solution at the moment.

**Comment by luoshuiyue** [comment]
I reconstruct the environment by `conda create -n cutie python=3.8 &&conda activate cutie && conda install pytorch=2.1 torchvision -c pytorch && conda install -e .` then the error disappeared.

**Comment by hkchengrex** [comment]
@luoshuiyue Great to know. Thank you for the update.
